{
 "title": "Xen",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   { "name": "node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Tactical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_pcpu_count_xen{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_memory_total_kib{instance=\"$node\"} * 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_running_domains{instance=\"$node\"}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum by (instance) (xen_host_cpu_usage_ratio{instance=~\"$node\"}) / count by (instance) (xen_host_cpu_usage_ratio{instance=~\"$node\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (xen_host_memory_free_kib{instance=~\"$node\"} / xen_host_memory_total_kib{instance=~\"$node\"}))* 100",
     "legendFormat": "RAM"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU stacked",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (instance) (xen_host_cpu_usage_ratio{instance=~\"$node\"}) / count by (instance) (xen_host_cpu_usage_ratio{instance=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * xen_host_cpu_usage_ratio{instance=~\"$node\"}",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "Non-idle cores",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "xen_host_running_vcpus{instance=~\"$node\"}",
     "legendFormat": "Running cores"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(xen_host_memory_total_kib{instance=~\"$node\"} * 1024) - (xen_host_memory_free_kib{instance=~\"$node\"} * 1024)",
     "legendFormat": "Used memory"
    },
    {
     "expr": "(xen_host_memory_total_kib{instance=~\"$node\"} * 1024)",
     "legendFormat": "Total memory"
    }
   ]
  }
 ]
}